### ISSUE TITLE
not "issue", but question

### ISSUE THREAD

**Issue by Juris3D** [McOmghall/time-enhancements-UE4-plugin#1]
Hello! I am wondering, is there any docs about your plugin(s), maybe examples of usage? This plugin, and procedural one. Thank You in advance, and - sorry if i am overlooking something obvious. :)

**Comment by McOmghall** [comment]
No problem at all, I haven't had the time to write proper examples for this one yet, and the code is being commented as I write it. I don't think I'll have other documentation than some small descriptions on the README.md.
