### ISSUE TITLE
421 is OK, 422 gives error (screenshot)

### ISSUE THREAD

**Issue by Juris3D** [McOmghall/time-enhancements-UE4-plugin#3]
Hello, not a complaint or anything, just informing, maybe useful :) On 4.21 all compiles and starts okay (VS2017), on 4.22 (also VS2017) gives those errors, in picture.

![Error422](https://user-images.githubusercontent.com/22710072/61533419-89005600-aa35-11e9-854b-92b6587929e0.jpg)

**Comment by McOmghall** [comment]
Thank you for reporting this! The plugin is 4.21-ready, but I will start soon updating it for 4.22.

**Comment by McOmghall** [comment]
Plugin should work on 4.22 and 4.23 now.
